@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #a0a0a0
  BackgroundColor #f8f8f8
}

[Metric Model] <<..metric>>
[Parser Registry] <<..registry>>
[Coverage Parsers] <<..parser>>

[Parser Registry] --> [Metric Model]
[Parser Registry] --> [Coverage Parsers]
[Coverage Parsers] -> [Metric Model]

@enduml
